version: '2'

services:
        web:
            build: .
            container_name: apis
            environment:
                    - APIS_DB_NAME=apis_package_full_18
                    - APIS_DB_USER=apis
                    - APIS_DB_PORT=3306
                    - APIS_DB_PASSWORD=Sen147Gta
                    - APIS_DB_HOST=100.92.49.181
                    - APIS_BASE_BRANCH=mpr
                    - DJANGO_SETTINGS_MODULE=apis.settings.server
            command: sh /start-apis/start.sh
            ports:
              - "8000:8000"
            volumes:
                    - ./start-apis:/start-apis
                    - ./staticfiles:/apis/apis-webpage-base/staticfiles
            stdin_open: true
            tty: true
        
        nginx:
            image: nginx:latest
            container_name: ngx
            ports:
                - "80:80"
            volumes:
                - ./nginx:/etc/nginx/conf.d
                - ./staticfiles:/staticfiles  
            depends_on:
                - web

