version: '2'

services:
        web:
            build: .
            container_name: apis_v2
            command: sh /start-apis/start.sh
            ports:
              - "8000:8000"
            volumes:
                    - ./start-apis:/start-apis
                    - ./staticfiles:/apis/apis-webpage-base/staticfiles
            stdin_open: true
            tty: true
        
        nginx:
            image: nginx:latest
            container_name: ngx_apis_v2
            ports:
                - "81:80"
            volumes:
                - ./nginx:/etc/nginx/conf.d
                - ./staticfiles:/staticfiles  
            depends_on:
                - web
            labels:
                    - traefik.backend=nginx
                    - traefik.frontend.rule=Host:mpr-test.sysiphos.arz.oeaw.ac.at
                    - traefik.docker.network=web
                    - traefik.port=80

